const SMCP = {
  facebook: {
    name: "Facebook",
    icon: "FaFacebook ",
    pack: "fa",
    base: "https://www.facebook.com/",
  },
  github: {
    name: "Github",
    icon: "FaGithub ",
    pack: "fa",
    base: "https://github.com/",
  },
  linkedin: {
    name: "Linkedin",
    icon: "FaLinkedin ",
    pack: "fa",
    base: "https://www.linkedin.com/in/",
  },
  codeforces: {
    name: "Codeforces",
    icon: "FaSquarePollVertical ",
    pack: "fa6",
    base: "https://codeforces.com/profile/",
  },
  youtube: {
    name: "Youtube",
    icon: "FaYoutube ",
    pack: "fa6",
    base: "https://www.youtube.com/",
  },
  instagram: {
    name: "Instagram",
    icon: "FaInstagram ",
    pack: "fa6",
    base: "https://www.instagram.com/",
  },
  stackoverflow: {
    name: "Stackoverflow",
    icon: "FaStackOverflow ",
    pack: "fa",
    base: "https://stackoverflow.com/users/",
  },
  twitter: {
    name: "Twitter",
    icon: "FaTwitter ",
    pack: "fa",
    base: "https://twitter.com/",
  },
  medium: {
    name: "Medium",
    icon: "FaMedium ",
    pack: "fa",
    base: "https://medium.com/",
  },
  dev: {
    name: "Dev",
    icon: "FaDev ",
    pack: "fa",
    base: "https://dev.to/",
  },
  discord: {
    name: "Discord",
    icon: "FaDiscord ",
    pack: "fa",
    base: "https://discord.com/",
  },
  telegram: {
    name: "Telegram",
    icon: "FaTelegram ",
    pack: "fa",
    base: "https://web.telegram.org/",
  },
  whatsapp: {
    name: "Whatsapp",
    icon: "FaWhatsapp ",
    pack: "fa",
    base: "https://web.whatsapp.com/",
  },
  snapchat: {
    name: "Snapchat",
    icon: "FaSnapchat ",
    pack: "fa",
    base: "https://www.snapchat.com/",
  },
  pinterest: {
    name: "Pinterest",
    icon: "FaPinterest ",
    pack: "fa",
    base: "https://www.pinterest.com/",
  },
  tumblr: {
    name: "Tumblr",
    icon: "FaTumblr ",
    pack: "fa",
    base: "https://www.tumblr.com/",
  },
  reddit: {
    name: "Reddit",
    icon: "FaReddit ",
    pack: "fa",
    base: "https://www.reddit.com/",
  },
  quora: {
    name: "Quora",
    icon: "FaQuora ",
    pack: "fa",
    base: "https://www.quora.com/",
  },
  behance: {
    name: "Behance",
    icon: "FaBehance ",
    pack: "fa",
    base: "https://www.behance.net/",
  },
  dribbble: {
    name: "Dribbble",
    icon: "FaDribbble ",
    pack: "fa",
    base: "https://dribbble.com/",
  },
  vimeo: {
    name: "Vimeo",
    icon: "FaVimeo ",
    pack: "fa",
    base: "https://vimeo.com/",
  },
  spotify: {
    name: "Spotify",
    icon: "FaSpotify ",
    pack: "fa",
    base: "https://open.spotify.com/",
  },
  googleplus: {
    name: "Google Plus",
    icon: "FaGooglePlusSquare",
    pack: "fa",
    base: "https://plus.google.com/",
  },
  codechef: {
    name: "Codechef",
    icon: "FaHatCowboy",
    pack: "fa6",
    base: "https://www.codechef.com/users/",
  },
  leetcode: {
    name: "Leetcode",
    icon: "FaCode ",
    pack: "fa6",
    base: "https://leetcode.com/",
  },
  hackerrank: {
    name: "Hackerrank",
    icon: "FaHackerrank ",
    pack: "fa6",
    base: "https://www.hackerrank.com/",
  },
  vjudge: {
    name: "Vjudge",
    icon: "FaCode ",
    pack: "fa6",
    base: "https://vjudge.net/user/",
  },
  atcoder: {
    name: "Atcoder",
    icon: "FaCode ",
    pack: "fa6",
    base: "https://atcoder.jp/users/",
  },
  hackerearth: {
    name: "Hackerearth",
    icon: "FaCode ",
    pack: "fa6",
    base: "https://www.hackerearth.com/",
  },
};

export default SMCP;
